newfold-labs/wp-module-hosting

includes/SSHInfo/SSHInfo.php
=> Panel: SSH Info use hostname

components/DataRefreshInfo/index.js, components/InfoActionCard/index.js, components/InformationTooltip/index.js, components/MalwareCheckCard/index.js, components/NameserversCard/getNameserversText.js, components/NameserversCard/index.js, components/Panel/index.js, components/SSHLoginInfoCard/getSSHLoginText.js, includes/HostingPanel/HostingPanel.php, includes/HostingPanel/RestApi/Controllers/HostingPanelController.php
=> Panel: Caching and Improvements

components/MalwareCheckCard/index.js, components/Panel/index.js, includes/HostingPanel/HostingPanel.php, includes/HostingPanel/RestApi/Controllers/HostingPanelController.php, includes/MalwareCheck/MalwareCheck.php
=> Panel: Cache Malware Checks

components/CDNCard/index.js, components/ObjectCachingCard/index.js, components/PHPVersionCard/index.js, components/Panel/index.js, components/SSHLoginInfoCard/index.js
=> Add Deep Links to MFE

components/CDNCard/index.js, components/ObjectCachingCard/index.js, components/Panel/index.js, components/SSHLoginInfoCard/index.js, includes/PlanInfo/PlanInfo.php
=> Add atomic specific redirects

includes/HostingPanel/HostingPanel.php
=> Add Brand Plugin sub-nav Support

components/Panel/getPanelText.js, components/Panel/index.js
=> Improve loader UI and hide Object Caching when not set up

includes/CDNInfo/CDNInfo.php
=> Support cache refactoring

includes/CDNInfo/CDNInfo.php
=> Update CF Usage

components/InfoActionCard/index.js, components/NameserversCard/index.js, tests/cypress/integration/nameservers.cy.js
Adding Cypress test for Nameservers card
=> Cypress: Nameservers

components/DataRefreshInfo/index.js, tests/cypress/integration/refreshdata.cy.js
Adding Cypress test for Refreshing Data button
=> Cypress: Refreshing data

components/MalwareCheckCard/index.js, tests/cypress/integration/malware-check.cy.js
=> Cypress: Malware Checks

.github/workflows/brand-plugin-test.yml
=> Cypress: Add Module Workflow

components/MalwareCheckCard/index.js, components/ObjectCachingCard/index.js, tests/cypress/integration/malware-check.cy.js, tests/cypress/integration/object-cache.cy.js
=> Cypress: Object Caching Checks

tests/cypress/integration/refreshdata.cy.js, tests/cypress/support/intercepts.js
=> Cypress: Fix Refresh Data Test

components/DataRefreshInfo/index.js, components/InfoActionCard/index.js, components/PHPVersionCard/getPHPVersionText.js, components/Panel/getPanelText.js, components/Panel/index.js, components/SSHLoginInfoCard/getSSHLoginText.js, components/SSHLoginInfoCard/index.js, components/SiteStatusCard/index.js, package-lock.json, package.json
This PR includes some improvements in the UI/UX of the hosting panel page ([PRESS10-176](https://jira.newfold.com/browse/PRESS10-176))
=> Hosting panel page style improvements

package-lock.json, package.json
=> Move `react-string-replace` to dependencies

includes/Helpers/HUAPIHelper.php
Related Hiive change: https://github.com/newfold-labs/laravel-hiive/pull/761
=> Add HUAPI Support via Reusable Helper

tests/cypress/integration/malware-check.cy.js
=> Match wp-json or index.php based on permalink structure

includes/HostingPanel/HostingPanel.php, tests/cypress/integration/flush-transient.cy.js
This PR add a small fix. It aims to flush the hosting panel cache transient on Permalinks structure changes in order to create a new transient with correct links
=> Flush panel cache transient on Permalinks structure changes

README.md
See: [PRESS10-47](https://jira.newfold.com/browse/PRESS10-47)
This PR adds the **_Critical Paths_** documentation into the Readme file
=> Add Critical Paths section in Readme file
